name: katze
description: "Katze App"
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  timezone: ^0.9.0
  dartz: ^0.10.1
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  bloc: ^8.1.4
  flutter_local_notifications: ^18.0.0
  app_links: ^6.3.2
  intl: any
  share_plus: ^10.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icon/

flutter_launcher_icons:
  android: true # Changed from "launcher_icon" to true
  adaptive_icon_background: "#111827" # Added for Android adaptive icon
  adaptive_icon_foreground: "assets/icon/katze-background.png" # Added for Android adaptive icon
  ios: true
  image_path: "assets/icon/katze-background.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/katze-background.png"
    background_color: "#111827"
    theme_color: "#e7d49e"
  windows:
    generate: true
    image_path: "assets/icon/katze-background.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/katze-background.png"
