name: katze
description: "Katze App"
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Einfaches State Management
  provider: ^6.0.0

  # Offline & Netzwerk
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  web_socket_channel: ^3.0.1

  # Zeitzonen
  timezone: ^0.9.0
  intl: ^0.19.0

  # Notifications
  flutter_local_notifications: ^18.0.0

  # Deep Linking
  app_links: ^6.3.2
  
  # UI
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9

  # Functionality
  uuid: ^4.5.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icon/

flutter_launcher_icons:
  android: true # Changed from "launcher_icon" to true
  adaptive_icon_background: "#111827" # Added for Android adaptive icon
  adaptive_icon_foreground: "assets/icon/katze-background.png" # Added for Android adaptive icon
  ios: true
  image_path: "assets/icon/katze-background.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/katze-background.png"
    background_color: "#111827"
    theme_color: "#e7d49e"
  windows:
    generate: true
    image_path: "assets/icon/katze-background.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/katze-background.png"
